cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartView.as_view(), name='summary'),
    path('shop/', views.ProductListView.as_view(), name='product-list'),
    path('shop/<slug>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('increase-quantity/<pk>/',
         views.IncreaseQuantityView.as_view(), name='increase-quantity'),
    path('decrease-quantity/<pk>/',
         views.DecreaseQuantityView.as_view(), name='decrease-quantity'),
    path('remove-from-cart/<pk>/',
         views.RemoveFromCartView.as_view(), name='remove-from-cart'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('payment/', views.PaymentView.as_view(), name='payment'),
    path('thank-you/', views.ThankYouView.as_view(), name='thank-you'),
    path('confirm-order/', views.ConfirmOrderView.as_view(), name='confirm-order'),
    path('orders/<pk>/', views.OrderDetailView.as_view(), name='order-detail'),
    path('addcomment/<int:id>', views.addcomment, name='addcomment'),
    path('payment/stripe/', views.StripePaymentView.as_view(), name='payment-stripe'),
    path('webhooks/stripe/', views.stripe_webhook_view, name='stripe-webhook'),

]

ecom/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', views.HomeView.as_view(), name='home'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('staff/', include('staff.urls', namespace='staff')),
    path('profile/', views.ProfileView.as_view(), name='profile')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

staff/urls.py
from django.urls import path
from . import views

app_name = 'staff'

urlpatterns = [
    path('', views.StaffView.as_view(), name='staff'),
    path('create/', views.ProductCreateView.as_view(), name='product-create'),
    path('products/', views.ProductListView.as_view(), name='product-list'),
    path('products/<pk>/update/',
         views.ProductUpdateView.as_view(), name='product-update'),
    path('products/<pk>/delete/',
         views.ProductDeleteView.as_view(), name='product-delete'),
]

templates/base.html
{% load static %}
{% load cart_template_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Django Ecom {% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'icons/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'icons/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'icons/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'icons/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'icons/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'icons/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'icons/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'icons/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'icons/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'icons/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'icons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'icons/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'icons/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'icons/manifest.json' %}">

    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'icons/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mukta:300,400,700">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css"
          integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous"/>
</head>

<body>

<div class="site-wrap">
    <header class="site-navbar" role="banner">
        <div class="site-navbar-top">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-6 col-md-8 mb-3 mb-md-0 col-md-4 order-1 order-md-2">
                        <div>
                            <a href="{% url 'home' %}">
                                <img class="img-fluid" src="{% static 'images/logo.png' %}" style="max-width: 150px;"/>
                            </a>
                        </div>
                    </div>

                    <div class="col-6 col-md-4 order-3 order-md-3 text-right">
                        <div class="site-top-icons">
                            <ul>
                                <li>
                                    {% if request.user.is_authenticated %}
                                        <a href="{% url 'profile' %}"><span><i class="fas fa-user"></i></span></a>
                                    {% else %}
                                        <a href="{% url 'account_login' %}"><span><i
                                                class="fas fa-sign-in-alt"></i></span></a>
                                    {% endif %}
                                </li>
                                <li>
                                    <a href="{% url 'cart:summary' %}" class="site-cart">
                                        <span><i class="fas fa-shopping-cart"></i></span>
                                        <span class="count">{{ request|cart_item_count }}</span>
                                    </a>
                                </li>
                                <li class="d-inline-block d-md-none ml-md-0">
                                    <a href="#" class="site-menu-toggle js-menu-toggle">
                                        <span><i class="fas fa-bars"></i></span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        {% include 'navbar.html' %}
        {% if messages %}
            {% for message in messages %}
                <div class="alert text-center alert-success alert-dismissible fade show"
                    role="alert">
                    {{ message }} 
                    <button type="button"
                        class="close"
                        data-dismiss="alert"
                        aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        {% endif %}

    </header>

    {% block content %}
    {% endblock content %}

    {% include 'footer.html' %}

</div>

{% include 'scripts.html' %}

{% block scripts %}
{% endblock scripts %}

</body>
</html>

templates/contact.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'home' %}">Home</a>
                <span class="mx-2 mb-0">/</span>
                <strong class="text-black">Contact</strong>
            </div>
        </div>
    </div>
</div>

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-7">
                <h2 class="h3 mb-3 text-black">Get in touch</h2>
            </div>
            <div class="col-md-7">
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input type="submit" class="btn btn-primary btn-lg btn-block" value="Submit message" />
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

templates/footer.html
<footer class="site-footer border-top">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-12">
                <p>
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script>
                    All rights reserved | This website is made with <i class="fas fa-heart"></i>
                </p>
            </div>
        </div>
    </div>
</footer>

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="site-blocks-cover" style="background-image: url({% static 'images/hero.jpg' %});" data-aos="fade">
    <div class="container">
        <div class="row">
            <div class="col-md-4 pt-5 pt-md-0">
            </div>
        </div>
    </div>
</div>

<div class="site-section site-section-sm site-blocks-1">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4" data-aos="fade-up" data-aos-delay="">
                <div class="icon mr-4 align-self-start">
                    <span><i class="fab fa-cc-paypal"></i></span>
                </div>
                <div class="text">
                    <h2 class="text-uppercase">Pay with Paypal</h2>
                    <p>Use server-side PayPal integration for handling payments.</p>
                </div>
            </div>
            <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4" data-aos="fade-up" data-aos-delay="100">
                <svg style="width: 100px; margin-right: 10px;" role="img" xmlns="http://www.w3.org/2000/svg"
                    fill="#1f4f7c" viewBox="0 0 24 24">
                    <title>Django icon</title>
                    <path
                        d="M11.146 0h3.924v18.165c-2.013.382-3.491.535-5.096.535-4.791 0-7.288-2.166-7.288-6.32 0-4.001 2.65-6.6 6.753-6.6.637 0 1.121.051 1.707.204V0zm0 9.143a3.894 3.894 0 0 0-1.325-.204c-1.988 0-3.134 1.223-3.134 3.364 0 2.09 1.096 3.236 3.109 3.236.433 0 .79-.025 1.35-.102V9.142zM21.314 6.06v9.097c0 3.134-.229 4.638-.917 5.937-.637 1.249-1.478 2.039-3.211 2.905l-3.644-1.733c1.733-.815 2.574-1.529 3.109-2.625.561-1.121.739-2.421.739-5.835V6.059h3.924zM17.39.021h3.924v4.026H17.39V.021z" />
                </svg>
                <div class="text">
                    <h2 class="text-uppercase">Made with Django</h2>
                    <p>Django makes it easy to quickly build awesome web apps.</p>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/navbar.html
<nav class="site-navigation text-right text-md-center" role="navigation">
    <div class="container">
        <ul class="site-menu js-clone-nav d-none d-md-block" style="padding: 0;">
            <li><a href="/">Home</a></li>
            <li><a href="{% url 'cart:product-list' %}">Shop</a></li>
            <li><a href="{% url 'contact' %}">Contact</a></li>
            {% if request.user.is_staff %}
                <li><a href="{% url 'staff:staff' %}">Staff</a></li>
            {% endif %}
        </ul>
    </div>
</nav>

templates/order.html
{% extends "base.html" %}

{% block content %}

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <a href="{% url 'profile' %}">Back to profile</a>
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">
                            Order: #{{ order.reference_number }}
                        </h5>
                        <h6 class="card-subtitle mb-2 text-muted">Ordered on: {{ order.ordered_date }}</h6>
                        <hr />
                        <div class="site-blocks-table">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Product.</th>
                                        <th>Total</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for item in order.items.all %}
                                    <tr>
                                        <td>{{ item.size.name }}, {{ item.colour.name }} of {{ item.product.title }} x
                                            {{ item.quantity }}</td>
                                        <td>${{ item.get_total_item_price }}</td>
                                    </tr>
                                    {% endfor %}
                                    <tr>
                                        <td>Subtotal</td>
                                        <td>${{ order.get_subtotal }}</td>
                                    </tr>
                                    <tr>
                                        <td>Total</td>
                                        <td>${{ order.get_total }}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/profile.html
{% extends "base.html" %}

{% block content %}

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <h2 class="text-black">Your profile</h2>
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">
                            {{ request.user.email }}
                            <a href="{% url 'account_logout' %}">
                                <small class="float-right">Logout</small></a>
                        </h5>
                        <hr />
                        <h5 class="card-title">Your orders</h5>
                        <div class="site-blocks-table">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Reference No.</th>
                                        <th>Date</th>
                                        <th>Amount</th>
                                        <th>Payment Status</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for order in orders %}
                                    <tr>
                                        <td><a href="{% url 'cart:order-detail' order.pk %}">#{{ order.reference_number }}</a></td>
                                        <td>{{ order.ordered_date }}</td>
                                        <td>${{ order.get_total }}</td>
                                        <td>{% if order.ordered %}Paid{% else %}Not paid{% endif %}</td>
                                    </tr>
                                    {% empty %}
                                    <tr>
                                        <td colspan="4">You haven't made any orders</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/scripts.html
{% load static %}

<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>